### ISSUE TITLE
Mod incompatibilities/crashes

### ISSUE THREAD

**Issue by TheNimbleNinja** [TwelvianZeta/Zetamod#9]
https://gist.github.com/TheNimbleNinja/40fad5418e2e224200a78b995d1ca3a0

**Comment by MicherGit** [comment]
This is due to a lithium incompatibility, due to mismatched method access. Will try to fix in 1.0.2. For now, remove lithium or zm.

**Comment by TwelvianZeta** [comment]
Can you check if it still affects 1.0.5?

**Comment by TheNimbleNinja** [comment]
https://gist.githubusercontent.com/natanfudge/f129b54f8b0e2682eb295293d4ef10de/raw/cff156305ffda89214baec3ccaf78633d2796345/crash.txt new type of crash

**Comment by TheNimbleNinja** [comment]
this crash happened after adding your mod back into the pack on creating new world

**Comment by TwelvianZeta** [comment]
Can you check on 1.0.6-pre?

**Comment by TwelvianZeta** [comment]
Here https://www.curseforge.com/minecraft/mc-mods/zetamod/files/3359253

**Comment by TwelvianZeta** [comment]
If you aren't experiencing any more crashes I will mark this as resolved.

**Comment by TheNimbleNinja** [comment]
ill check and see if it crashes when i can
